CREATE DATABASE IF NOT EXISTS PROJECT;

USE PROJECT;

CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
	`ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`FIRSTNAME` VARCHAR(50) NULL DEFAULT NULL,
	`LASTNAME` VARCHAR(50) NULL DEFAULT NULL,
	`BIRTH_DATE` DATE NOT NULL,
	`CELL_PHONE` VARCHAR(15) NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='LATIN1_SWEDISH_CI'
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=606;

CREATE TABLE IF NOT EXISTS `CONTROL_PROCESS` (
	`ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CONTROL_PROCESS_ID` VARCHAR(100) NOT NULL,
	`USERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`START_TIME` DATE NOT NULL,
	`END_TIME` DATE NOT NULL,
	`PROCESS_TYPE` VARCHAR(50) NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `CONTROL_PROCESS_DETAIL` (
	`CONTROL_PROCESS_DETAIL_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CONTROL_PROCESS_ID` BIGINT(10) NOT NULL,
	
	`CONTROLFILENAME` VARCHAR(100) NULL DEFAULT NULL,
	`DATFILENAME` VARCHAR(100) NULL DEFAULT NULL,
	`METAFILENAME` VARCHAR(100) NULL DEFAULT NULL,
	
	`HDFSCTLFILELOC` VARCHAR(100) NULL DEFAULT NULL,
	`HDFSMETAFILELOC` VARCHAR(50) NULL DEFAULT NULL,
	`HDFSDATFILELOC` VARCHAR(50) NULL DEFAULT NULL,
	
	`SCHEMAVALIDATION` VARCHAR(50) NULL DEFAULT NULL,
	`ROWCOUNTVALIDATION` VARCHAR(50) NULL DEFAULT NULL,
	`CRCVALIDATION` VARCHAR(50) NULL DEFAULT NULL,
	
	`CTLROWCOUNTEXIST` TINYINT NOT NULL DEFAULT 0,
	`CTLROWCOUNT` BIGINT(10) NOT NULL,
	`COMPUTEDROWCOUNT` BIGINT(10) NOT NULL,
	
	`DETAILLOGFILELOC` VARCHAR(500) NOT NULL,
	
	`INSERTEDDATE` DATE NOT NULL,
	`UPDATEDDATE` DATE NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (`CONTROL_PROCESS_DETAIL_ID`),
	FOREIGN KEY (CONTROL_PROCESS_ID) REFERENCES CONTROL_PROCESS(ID)
);

	